### ISSUE TITLE
Missing syntax highlighting

### ISSUE THREAD

**Issue by EVODelavega** [fallenwood/vscode-viml#2]
Some keywords aren't highlighted ATM. At first glance, `*abbrev`, `call` and `color` aren't matched by the regex (although `colorscheme` is).

Perhaps a list of special variables, to be highlighted in a specific way would be worth adding. Things like `$MYVIMRC`, `tabstop`, `shiftwidth`, and `mapleader`... ?

As a side-note: I can't help but notice your repo doesn't specify a license. AFAIK, most VSCode extensions use the MIT license. It might be worth adding that for clarity (and to encourage contributors). I've included the MIT license in my PR (granting you copyright, of course)

**Comment by fallenwood** [comment]
thanks
